-- Insert some sample data into the 'tasks' table
INSERT INTO TASK (task_name, description, is_completed) VALUES
('Buy groceries', 'Purchase fruits, vegetables, and milk from the store.', FALSE),
('Finish project report', 'Complete the quarterly financial analysis report.', FALSE),
('Call mom', 'Catch up with mom over the weekend.', TRUE),
('Call school', 'Catch up with yomger kids school over the weekend.', TRUE),
('Call college', 'Catch up with elder kids college over the weekend.', TRUE),
('Schedule dentist appointment', 'Book an appointment for next Thursday.', FALSE),
('Workout session', 'Go to the gym for cardio and weights.', FALSE),
('Pay electricity bill', 'Pay the monthly utility bill online.', TRUE),
('Team meeting', 'Weekly sync-up with the software development team.', TRUE),
('Plan vacation', 'Research destinations and flights for summer break.', FALSE),
('Clean the house', 'Vacuum, dust, and tidy up the living room.', FALSE),
('Read a book', 'Finish reading the current novel.', TRUE),
('Update resume', 'Add recent work experience and projects.', FALSE),
('Backup files', 'Backup important documents to cloud storage.', TRUE),
('Buy birthday gift', 'Get a present for Sarah’s birthday.', FALSE),
('Organize desk', 'Sort paperwork and clean the workspace.', TRUE),
('Submit tax documents', 'File taxes before the deadline.', FALSE),
('Plan weekly meals', 'Prepare a meal plan and grocery list.', FALSE),
('Send emails', 'Respond to pending client messages.', TRUE),
('Wash the car', 'Clean the exterior and interior of the car.', FALSE),
('Water plants', 'Water indoor plants and garden flowers.', TRUE),
('Book flight tickets', 'Purchase tickets for business trip to New York.', FALSE),
('Study SQL', 'Practice database queries and joins.', TRUE),
('Install software updates', 'Update system and applications to latest versions.', TRUE),
('Prepare presentation', 'Create slides for Monday’s team meeting.', FALSE),
('Clean kitchen', 'Wash dishes and sanitize countertops.', TRUE),
('Buy new shoes', 'Find a pair of comfortable running shoes.', FALSE),
('Attend webinar', 'Join the data science webinar at 3 PM.', TRUE),
('Renew driver’s license', 'Visit DMV to renew before expiration.', FALSE),
('Make dinner', 'Cook pasta and salad for family dinner.', TRUE),
('Research new phone', 'Compare specs and prices of new models.', FALSE),
('Fix leaking faucet', 'Repair the kitchen sink faucet.', TRUE),
('Print documents', 'Print project proposal and reports.', FALSE),
('Collect documents', 'collect documents from owner.', FALSE),
('Laundry day', 'Wash and fold clothes.', TRUE),
('Meditate', '10-minute morning meditation session.', TRUE),
('Call plumber', 'Schedule an appointment for bathroom repair.', FALSE),
('Post office visit', 'Send out package and buy stamps.', TRUE),
('Check emails', 'Go through and organize inbox.', TRUE),
('send emails', 'Send email invite to all apartment residents.', TRUE),
('Buy dog food', 'Get food and treats for the dog.', FALSE),
('visit dog doctor', 'visit doctor for the dog.', FALSE),
('Walk the dog', 'Take dog for an evening walk.', TRUE),
('Cook breakfast', 'Prepare omelette and toast.', TRUE),
('Reply to messages', 'Respond to pending WhatsApp and Slack messages.', TRUE),
('Plan birthday party', 'Organize decorations, cake, and invitations.', FALSE),
('Set up budget tracker', 'Use spreadsheet to track monthly expenses.', FALSE),
('Call bank', 'Inquire about credit card limit increase.', FALSE),
('Call Friend', 'Inquire about next weekend plan.', FALSE),
('Test app feature', 'Verify new user authentication flow.', TRUE),
('Write blog post', 'Publish an article on productivity tips.', FALSE),
('Clean garage', 'Sort tools and discard unused items.', FALSE),
('Watch tutorial', 'Learn about Docker basics.', TRUE),
('Watch movie', 'Watch pending web series.', FALSE),
('Check investments', 'Review stock portfolio and make adjustments.', TRUE),
('Update LinkedIn profile', 'Add certifications and skills.', FALSE);